# Source: https://squidfunk.github.io/mkdocs-material/publishing-your-site/?h=workflow#with-github-actions
name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: pip install mkdocs-material 
      - run: pip install mkdocs-rss-plugin

      - name: Build and deploy to GitHub Pages 🏗️ 🚀
        env:
          CI: true
        run: mkdocs gh-deploy --force